### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jagajaga** [frankosterfeld/qtkeychain#42]
Trying to install this pkg to NixOs. And getting error at the end. After it was succesfully built.

```
CMake Error at cmake_install.cmake:44 (FILE):
  file INSTALL cannot copy file
  "/tmp/nix-build-qtkeychain-0.3.0.drv-0/qtkeychain-0.3.0/build/qtkeychain_de.qm"
  to
  "/nix/store/a3gcql20apdznblj4hg950mc50nd3lsk-qt-4.8.6/share/qt-4.8.6/translations/qtkeychain_de.qm".
```

Where should I look to get the origin of the error?
Or may be you know what's that?

**Comment by jensseidel** [comment]
Hi,

I was also affected by the error

CMake Error at cmake_install.cmake:44 (FILE):
  file INSTALL cannot copy file
  "/HOME1/users/personal/jese/Software/ownCloud/qtkeychain/build/qtkeychain_de.qm"
  to "/usr/share/qt4/translations/qtkeychain_de.qm".

after compiling with 
cmake -DCMAKE_INSTALL_PREFIX=~/local ..
make install

The problem is that QT_TRANSLATIONS_DIR is set to /usr/share/qt4/translations (I have a Qt4 installation) and this is not writeable ... I changed it manually in cmake_install.cmake to ~/local/share/... even if these files will not be used (or is there a way?).

**Comment by Millak** [comment]
here's what I put for guix to move the translations from qt5/translations to qtkeychain/share/qtkeychain/translations

(define-public qtkeychain
  (package
    (name "qtkeychain")
    (version "0.5.0")
    (source
      (origin
        (method url-fetch)
        (uri (string-append "https://github.com/frankosterfeld/qtkeychain/"
                            "archive/v" version ".tar.gz"))
        (file-name (string-append name "-" version ".tar.gz"))
        (sha256
         (base32 "055mkd4pz6cyff4cw0784wjc1w92m8x223sxi96ph15fr3lplbg6"))))
    (build-system cmake-build-system)
    (inputs
     `(("qt", qt)))
    (arguments
     `(#:tests? #f ; No tests included
       #:phases
       (modify-phases
         %standard-phases
         (add-before
          'configure 'set-qt-trans-dir
           (lambda _
             (substitute* "CMakeLists.txt"
              (("\\$\\{qt_translations_dir\\}")
                "${CMAKE_INSTALL_PREFIX}/share/qtkeychain/translations")))))))
    (home-page "https://github.com/frankosterfeld/qtkeychain")
    (synopsis "Qt API to store passwords")
    (description
      "QtKeychain is a Qt API to store passwords and other secret data
securely.  It will not store any data unencrypted unless explicitly requested.")
    (license bsd-3)))

so in the root dir of the source, in CMakeLists.txt, I changed all (1) instances of ${qt_translations_dir} to ${CMAKE_INSTALL_PREFIX}/share/qtkeychain/translations

**Comment by KitsuneRal** [comment]
I found a better workaround - pass `-DQT_TRANSLATIONS_DIR=<desired directory>` to CMake. But generally, using Qt's own translations directory looks quite wrong exactly because of reasons above: Qt can be a system library while QtKeychain gets installed to a prefix. Even if Qt is installed in a world-readable location, throwing translation files inside of it contaminates the given Qt installation and produces hard to find problems when you, e.g., have 2 Qt instances on the same machine. `${CMAKE_INSTALL_DATADIR}/${QTKEYCHAIN_TARGET_NAME}/translations` looks a much better place.
